Insert into mst_company (id, id2, is_active, name) values ('BBDO','BD',1,'Blue Bird (2)');
Insert into mst_company (id, id2, is_active, name) values ('BBPO','BP',1,'Blue Bird Pusaka');
Insert into mst_company (id, id2, is_active, name) values ('BGBO','BG',1,'Big Bird');
Insert into mst_company (id, id2, is_active, name) values ('BGPO','BA',1,'Big Bird Pusaka');
Insert into mst_company (id, id2, is_active, name) values ('BLBO','BB',1,'Blue Bird Taxi');
Insert into mst_company (id, id2, is_active, name) values ('CARO','CR',1,'CaReady');
Insert into mst_company (id, id2, is_active, name) values ('CNEO','CE',1,'Central Naga Europindo');
Insert into mst_company (id, id2, is_active, name) values ('CPJO','CP',1,'Cendrawasih Pertiwi Jaya');
Insert into mst_company (id, id2, is_active, name) values ('GBBO','GB',1,'Golden Bird Bali');
Insert into mst_company (id, id2, is_active, name) values ('GBMO','GM',1,'Golden Bird Metro');
Insert into mst_company (id, id2, is_active, name) values ('IMTO','IM',1,'Irdawan Multitrans');
Insert into mst_company (id, id2, is_active, name) values ('KBBO','KB',1,'Kawan Blue Bird');
Insert into mst_company (id, id2, is_active, name) values ('LBTO','LB',1,'Lintas Buana');
Insert into mst_company (id, id2, is_active, name) values ('LSKO','LS',1,'Luhur Satria Sejati Kencana');
Insert into mst_company (id, id2, is_active, name) values ('LTBO','LT',1,'Lombok Taksi');
Insert into mst_company (id, id2, is_active, name) values ('LTUO','LU',1,'Lombok Taksi Utama');
Insert into mst_company (id, id2, is_active, name) values ('MRTO','MJ',1,'Morante Jaya');
Insert into mst_company (id, id2, is_active, name) values ('PBTO','PB',1,'Praja Bali Transportation');
Insert into mst_company (id, id2, is_active, name) values ('PNUO','PU',1,'Pusaka Nuri utama');
Insert into mst_company (id, id2, is_active, name) values ('PPTO','PP',1,'Pusaka Prima Transport');
Insert into mst_company (id, id2, is_active, name) values ('PSAO','PA',1,'Prima Sarijati Agung');
Insert into mst_company (id, id2, is_active, name) values ('PSUO','PS',1,'Pusaka Satria Utama');
Insert into mst_company (id, id2, is_active, name) values ('SLBO','SB',1,'Silver Bird');
Insert into mst_company (id, id2, is_active, name) values ('STUO','SU',1,'Surabaya Taksi Utama');
Insert into mst_company (id, id2, is_active, name) values ('TANO','TN',1,'Trans Antar Nusabird');
